### ISSUE TITLE
Error in Segment Image Data notebok when making overlay using > 3 total nuclear and membrane channels

### ISSUE THREAD

**Issue by awedwards** [angelolab/ark-analysis#284] opened 2020-10-21 22:08 UTC
**Describe the bug**
Using more than 3 total nuclear and membrane channels for segmentation produces an error in the overlay visualization step in Segment_Image_Data notebook.

**To Reproduce**
1. Set mibitiff = true, though I don't know if this is necessary to reproduce
2. I added 2 nuclear channels and 3 membrane channels
3. Run notebook until cell 9 (titled "We can also then save the segmented mask overlaid on the imaging data")
4. Try to generate overlays
5. See error below

**Expected behavior**
Expect to get an overlay with the proper addition of the nuclear and membrane channels , as referenced in #272 .

I can get around this error by manually feeding the plot_overlay function just a selection of the nuclear and membrane channels, as long as I just feed it 3 or les.

**Error Trace**
```
ValueError                                Traceback (most recent call last)
<ipython-input-9-f71583686a6c> in <module>
      2     plot_utils.plot_overlay(segmentation_labels.loc[fov, :, :, "whole_cell"].values,
      3                             data_xr.loc[fov, :, :, :].values,
----> 4                             path=os.path.join(deepcell_output_dir, f'{fov.values}_overlay.tif'))

/usr/local/lib/python3.6/site-packages/ark/utils/plot_utils.py in plot_overlay(predicted_contour, plotting_tif, alternate_contour, path)
     56             else:
     57                 raise ValueError("only 3 channels of overlay supported, got {}".
---> 58                                  format(plotting_tif.shape))
     59         else:
     60             raise ValueError("plotting tif must be 2D or 3D array, got {}".

ValueError: only 3 channels of overlay supported, got (2048, 2048, 5)

```

**Comment by awedwards** [comment] 2020-11-30 22:21
This seems to be broken again in the latest notebook.

**Comment by awedwards** [comment] 2020-11-30 22:33
Using two nuclear channels and three membrane channels:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-431d6fd2bdad> in <module>
      7     segmentation_labels_xr=segmentation_labels,
      8     fovs=data_xr[:,:,:,0].fovs.values, channel_data_xr=data_xr,
----> 9     chan_list=overlay_channels, output_dir=viz_dir, show=True)

/usr/local/lib/python3.6/site-packages/ark/utils/segmentation_utils.py in visualize_segmentation(segmentation_labels_xr, channel_data_xr, output_dir, chan_list, fovs, show)
    223                 labels,
    224                 plotting_tif=input_data,
--> 225                 path=os.path.join(output_dir, save_path), show=show
    226             )
    227         # Generates segmentation borders and labels

/usr/local/lib/python3.6/site-packages/ark/utils/plot_utils.py in plot_overlay(predicted_contour, plotting_tif, alternate_contour, path, show)
     58             else:
     59                 raise ValueError("only 3 channels of overlay supported, got {}".
---> 60                                  format(plotting_tif.shape))
     61         else:
     62             raise ValueError("plotting tif must be 2D or 3D array, got {}".

ValueError: only 3 channels of overlay supported, got (2048, 2048, 5)
```

**Comment by alex-l-kong** [comment] 2020-12-01 01:20
@awedwards @ngreenwald looks like the issue is that for some reason, the notebook reads in the summed channel data but still visualizes it on the un-summed channel data. This will be fixed.

**Closed** 2020-12-03 19:26 UTC
Labels: bug
